/*
 * Bitget Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitget.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.bitget.openapi.model.MarginOrderRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bitget.openapi.JSON;

/**
 * MarginBatchOrdersRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MarginBatchOrdersRequest {
  public static final String SERIALIZED_NAME_CHANNEL_API_CODE = "channelApiCode";
  @SerializedName(SERIALIZED_NAME_CHANNEL_API_CODE)
  private String channelApiCode;

  public static final String SERIALIZED_NAME_IP = "ip";
  @SerializedName(SERIALIZED_NAME_IP)
  private String ip;

  public static final String SERIALIZED_NAME_ORDER_LIST = "orderList";
  @SerializedName(SERIALIZED_NAME_ORDER_LIST)
  private List<MarginOrderRequest> orderList = null;

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";
  @SerializedName(SERIALIZED_NAME_SYMBOL)
  private String symbol;

  public MarginBatchOrdersRequest() {
  }

  public MarginBatchOrdersRequest channelApiCode(String channelApiCode) {
    
    this.channelApiCode = channelApiCode;
    return this;
  }

   /**
   * Get channelApiCode
   * @return channelApiCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChannelApiCode() {
    return channelApiCode;
  }


  public void setChannelApiCode(String channelApiCode) {
    this.channelApiCode = channelApiCode;
  }


  public MarginBatchOrdersRequest ip(String ip) {
    
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIp() {
    return ip;
  }


  public void setIp(String ip) {
    this.ip = ip;
  }


  public MarginBatchOrdersRequest orderList(List<MarginOrderRequest> orderList) {
    
    this.orderList = orderList;
    return this;
  }

  public MarginBatchOrdersRequest addOrderListItem(MarginOrderRequest orderListItem) {
    if (this.orderList == null) {
      this.orderList = new ArrayList<>();
    }
    this.orderList.add(orderListItem);
    return this;
  }

   /**
   * Get orderList
   * @return orderList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<MarginOrderRequest> getOrderList() {
    return orderList;
  }


  public void setOrderList(List<MarginOrderRequest> orderList) {
    this.orderList = orderList;
  }


  public MarginBatchOrdersRequest symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * symbol
   * @return symbol
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "BTCUSDT_SPBL", required = true, value = "symbol")

  public String getSymbol() {
    return symbol;
  }


  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MarginBatchOrdersRequest instance itself
   */
  public MarginBatchOrdersRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarginBatchOrdersRequest marginBatchOrdersRequest = (MarginBatchOrdersRequest) o;
    return Objects.equals(this.channelApiCode, marginBatchOrdersRequest.channelApiCode) &&
        Objects.equals(this.ip, marginBatchOrdersRequest.ip) &&
        Objects.equals(this.orderList, marginBatchOrdersRequest.orderList) &&
        Objects.equals(this.symbol, marginBatchOrdersRequest.symbol)&&
        Objects.equals(this.additionalProperties, marginBatchOrdersRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelApiCode, ip, orderList, symbol, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarginBatchOrdersRequest {\n");
    sb.append("    channelApiCode: ").append(toIndentedString(channelApiCode)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    orderList: ").append(toIndentedString(orderList)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("channelApiCode");
    openapiFields.add("ip");
    openapiFields.add("orderList");
    openapiFields.add("symbol");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("symbol");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MarginBatchOrdersRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!MarginBatchOrdersRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MarginBatchOrdersRequest is not found in the empty JSON string", MarginBatchOrdersRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MarginBatchOrdersRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("channelApiCode") != null && !jsonObj.get("channelApiCode").isJsonNull()) && !jsonObj.get("channelApiCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelApiCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelApiCode").toString()));
      }
      if ((jsonObj.get("ip") != null && !jsonObj.get("ip").isJsonNull()) && !jsonObj.get("ip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ip").toString()));
      }
      if (jsonObj.get("orderList") != null && !jsonObj.get("orderList").isJsonNull()) {
        JsonArray jsonArrayorderList = jsonObj.getAsJsonArray("orderList");
        if (jsonArrayorderList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("orderList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `orderList` to be an array in the JSON string but got `%s`", jsonObj.get("orderList").toString()));
          }

          // validate the optional field `orderList` (array)
          for (int i = 0; i < jsonArrayorderList.size(); i++) {
            MarginOrderRequest.validateJsonObject(jsonArrayorderList.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("symbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MarginBatchOrdersRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MarginBatchOrdersRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MarginBatchOrdersRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MarginBatchOrdersRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<MarginBatchOrdersRequest>() {
           @Override
           public void write(JsonWriter out, MarginBatchOrdersRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public MarginBatchOrdersRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             MarginBatchOrdersRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MarginBatchOrdersRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MarginBatchOrdersRequest
  * @throws IOException if the JSON string is invalid with respect to MarginBatchOrdersRequest
  */
  public static MarginBatchOrdersRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MarginBatchOrdersRequest.class);
  }

 /**
  * Convert an instance of MarginBatchOrdersRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

