/*
 * Bitget Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitget.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.bitget.openapi.model.OrderPaymentDetailInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bitget.openapi.JSON;

/**
 * MerchantOrderPaymentInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MerchantOrderPaymentInfo {
  public static final String SERIALIZED_NAME_PAYMETHOD_ID = "paymethodId";
  @SerializedName(SERIALIZED_NAME_PAYMETHOD_ID)
  private String paymethodId;

  public static final String SERIALIZED_NAME_PAYMETHOD_INFO = "paymethodInfo";
  @SerializedName(SERIALIZED_NAME_PAYMETHOD_INFO)
  private List<OrderPaymentDetailInfo> paymethodInfo = null;

  public static final String SERIALIZED_NAME_PAYMETHOD_NAME = "paymethodName";
  @SerializedName(SERIALIZED_NAME_PAYMETHOD_NAME)
  private String paymethodName;

  public MerchantOrderPaymentInfo() {
  }

  public MerchantOrderPaymentInfo paymethodId(String paymethodId) {
    
    this.paymethodId = paymethodId;
    return this;
  }

   /**
   * Get paymethodId
   * @return paymethodId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPaymethodId() {
    return paymethodId;
  }


  public void setPaymethodId(String paymethodId) {
    this.paymethodId = paymethodId;
  }


  public MerchantOrderPaymentInfo paymethodInfo(List<OrderPaymentDetailInfo> paymethodInfo) {
    
    this.paymethodInfo = paymethodInfo;
    return this;
  }

  public MerchantOrderPaymentInfo addPaymethodInfoItem(OrderPaymentDetailInfo paymethodInfoItem) {
    if (this.paymethodInfo == null) {
      this.paymethodInfo = new ArrayList<>();
    }
    this.paymethodInfo.add(paymethodInfoItem);
    return this;
  }

   /**
   * Get paymethodInfo
   * @return paymethodInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OrderPaymentDetailInfo> getPaymethodInfo() {
    return paymethodInfo;
  }


  public void setPaymethodInfo(List<OrderPaymentDetailInfo> paymethodInfo) {
    this.paymethodInfo = paymethodInfo;
  }


  public MerchantOrderPaymentInfo paymethodName(String paymethodName) {
    
    this.paymethodName = paymethodName;
    return this;
  }

   /**
   * Get paymethodName
   * @return paymethodName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPaymethodName() {
    return paymethodName;
  }


  public void setPaymethodName(String paymethodName) {
    this.paymethodName = paymethodName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MerchantOrderPaymentInfo instance itself
   */
  public MerchantOrderPaymentInfo putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantOrderPaymentInfo merchantOrderPaymentInfo = (MerchantOrderPaymentInfo) o;
    return Objects.equals(this.paymethodId, merchantOrderPaymentInfo.paymethodId) &&
        Objects.equals(this.paymethodInfo, merchantOrderPaymentInfo.paymethodInfo) &&
        Objects.equals(this.paymethodName, merchantOrderPaymentInfo.paymethodName)&&
        Objects.equals(this.additionalProperties, merchantOrderPaymentInfo.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymethodId, paymethodInfo, paymethodName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantOrderPaymentInfo {\n");
    sb.append("    paymethodId: ").append(toIndentedString(paymethodId)).append("\n");
    sb.append("    paymethodInfo: ").append(toIndentedString(paymethodInfo)).append("\n");
    sb.append("    paymethodName: ").append(toIndentedString(paymethodName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("paymethodId");
    openapiFields.add("paymethodInfo");
    openapiFields.add("paymethodName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MerchantOrderPaymentInfo
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!MerchantOrderPaymentInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MerchantOrderPaymentInfo is not found in the empty JSON string", MerchantOrderPaymentInfo.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("paymethodId") != null && !jsonObj.get("paymethodId").isJsonNull()) && !jsonObj.get("paymethodId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymethodId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymethodId").toString()));
      }
      if (jsonObj.get("paymethodInfo") != null && !jsonObj.get("paymethodInfo").isJsonNull()) {
        JsonArray jsonArraypaymethodInfo = jsonObj.getAsJsonArray("paymethodInfo");
        if (jsonArraypaymethodInfo != null) {
          // ensure the json data is an array
          if (!jsonObj.get("paymethodInfo").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `paymethodInfo` to be an array in the JSON string but got `%s`", jsonObj.get("paymethodInfo").toString()));
          }

          // validate the optional field `paymethodInfo` (array)
          for (int i = 0; i < jsonArraypaymethodInfo.size(); i++) {
            OrderPaymentDetailInfo.validateJsonObject(jsonArraypaymethodInfo.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("paymethodName") != null && !jsonObj.get("paymethodName").isJsonNull()) && !jsonObj.get("paymethodName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymethodName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymethodName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MerchantOrderPaymentInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MerchantOrderPaymentInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MerchantOrderPaymentInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MerchantOrderPaymentInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<MerchantOrderPaymentInfo>() {
           @Override
           public void write(JsonWriter out, MerchantOrderPaymentInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public MerchantOrderPaymentInfo read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             MerchantOrderPaymentInfo instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MerchantOrderPaymentInfo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MerchantOrderPaymentInfo
  * @throws IOException if the JSON string is invalid with respect to MerchantOrderPaymentInfo
  */
  public static MerchantOrderPaymentInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MerchantOrderPaymentInfo.class);
  }

 /**
  * Convert an instance of MerchantOrderPaymentInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

