/*
Bitget Open API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MarginBatchCancelOrderRequest struct for MarginBatchCancelOrderRequest
type MarginBatchCancelOrderRequest struct {
	// clientOids
	ClientOids []string `json:"clientOids,omitempty"`
	// orderIds
	OrderIds []string `json:"orderIds,omitempty"`
	// symbol
	Symbol               string `json:"symbol"`
	AdditionalProperties map[string]interface{}
}

type _MarginBatchCancelOrderRequest MarginBatchCancelOrderRequest

// NewMarginBatchCancelOrderRequest instantiates a new MarginBatchCancelOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarginBatchCancelOrderRequest(symbol string) *MarginBatchCancelOrderRequest {
	this := MarginBatchCancelOrderRequest{}
	this.Symbol = symbol
	return &this
}

// NewMarginBatchCancelOrderRequestWithDefaults instantiates a new MarginBatchCancelOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarginBatchCancelOrderRequestWithDefaults() *MarginBatchCancelOrderRequest {
	this := MarginBatchCancelOrderRequest{}
	return &this
}

// GetClientOids returns the ClientOids field value if set, zero value otherwise.
func (o *MarginBatchCancelOrderRequest) GetClientOids() []string {
	if o == nil || isNil(o.ClientOids) {
		var ret []string
		return ret
	}
	return o.ClientOids
}

// GetClientOidsOk returns a tuple with the ClientOids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarginBatchCancelOrderRequest) GetClientOidsOk() ([]string, bool) {
	if o == nil || isNil(o.ClientOids) {
		return nil, false
	}
	return o.ClientOids, true
}

// HasClientOids returns a boolean if a field has been set.
func (o *MarginBatchCancelOrderRequest) HasClientOids() bool {
	if o != nil && !isNil(o.ClientOids) {
		return true
	}

	return false
}

// SetClientOids gets a reference to the given []string and assigns it to the ClientOids field.
func (o *MarginBatchCancelOrderRequest) SetClientOids(v []string) {
	o.ClientOids = v
}

// GetOrderIds returns the OrderIds field value if set, zero value otherwise.
func (o *MarginBatchCancelOrderRequest) GetOrderIds() []string {
	if o == nil || isNil(o.OrderIds) {
		var ret []string
		return ret
	}
	return o.OrderIds
}

// GetOrderIdsOk returns a tuple with the OrderIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarginBatchCancelOrderRequest) GetOrderIdsOk() ([]string, bool) {
	if o == nil || isNil(o.OrderIds) {
		return nil, false
	}
	return o.OrderIds, true
}

// HasOrderIds returns a boolean if a field has been set.
func (o *MarginBatchCancelOrderRequest) HasOrderIds() bool {
	if o != nil && !isNil(o.OrderIds) {
		return true
	}

	return false
}

// SetOrderIds gets a reference to the given []string and assigns it to the OrderIds field.
func (o *MarginBatchCancelOrderRequest) SetOrderIds(v []string) {
	o.OrderIds = v
}

// GetSymbol returns the Symbol field value
func (o *MarginBatchCancelOrderRequest) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *MarginBatchCancelOrderRequest) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *MarginBatchCancelOrderRequest) SetSymbol(v string) {
	o.Symbol = v
}

func (o MarginBatchCancelOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ClientOids) {
		toSerialize["clientOids"] = o.ClientOids
	}
	if !isNil(o.OrderIds) {
		toSerialize["orderIds"] = o.OrderIds
	}
	if true {
		toSerialize["symbol"] = o.Symbol
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *MarginBatchCancelOrderRequest) UnmarshalJSON(bytes []byte) (err error) {
	varMarginBatchCancelOrderRequest := _MarginBatchCancelOrderRequest{}

	if err = json.Unmarshal(bytes, &varMarginBatchCancelOrderRequest); err == nil {
		*o = MarginBatchCancelOrderRequest(varMarginBatchCancelOrderRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "clientOids")
		delete(additionalProperties, "orderIds")
		delete(additionalProperties, "symbol")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMarginBatchCancelOrderRequest struct {
	value *MarginBatchCancelOrderRequest
	isSet bool
}

func (v NullableMarginBatchCancelOrderRequest) Get() *MarginBatchCancelOrderRequest {
	return v.value
}

func (v *NullableMarginBatchCancelOrderRequest) Set(val *MarginBatchCancelOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMarginBatchCancelOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMarginBatchCancelOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarginBatchCancelOrderRequest(val *MarginBatchCancelOrderRequest) *NullableMarginBatchCancelOrderRequest {
	return &NullableMarginBatchCancelOrderRequest{value: val, isSet: true}
}

func (v NullableMarginBatchCancelOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarginBatchCancelOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
