# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import bitget
from bitget.paths.api_p2p_v1_merchant_order_list import get  # noqa: E501
from bitget import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiP2pV1MerchantOrderList(ApiTestMixin, unittest.TestCase):
    """
    ApiP2pV1MerchantOrderList unit test stubs
        orderList  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200

    def testApi(self):
        configuration = ApiTestMixin.get_default_configuration()
        # Enter a context with an instance of the API client
        with bitget.ApiClient(configuration) as api_client:
            # Create an instance of the API class
            from bitget.apis.tags import p2p_merchant_api
            api_instance = p2p_merchant_api.MerchantList(api_client)
            try:
                req = {
                    'online': "no",
                }
                api_response = api_instance.merchant_list(req)
                print(api_response)
                self.assertIsNotNone(api_response)
                self.assertIsNotNone(api_response.body)
                self.assertEqual(api_response.body['code'], '00000')
                self.assertEqual(api_response.body['msg'], 'success')
                self.assertIsNotNone(api_response.body['data']['resultList'])
                for item in api_response.body['data']['resultList']:
                    print(item)
                    self.assertIsNotNone(item['nickName'])
                    self.assertIsNotNone(item['merchantId'])
                    self.assertIsNotNone(item['isOnline'])
                    self.assertIsNotNone(item['averageRealese'])
                    self.assertIsNotNone(item['totalTrades'])
                    self.assertIsNotNone(item['thirtyTrades'])
                    self.assertIsNotNone(item['thirtyCompletionRate'])
            except bitget.ApiException as e:
                print("Exception when calling: %s\n" % e)


if __name__ == '__main__':
    unittest.main()
