# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest

import bitget
from bitget import configuration, api_client
from bitget.paths.api_margin_v1_cross_order_batch_place_order import post  # noqa: E501
from .. import ApiTestMixin


class TestApiMarginV1CrossOrderBatchPlaceOrder(ApiTestMixin, unittest.TestCase):
    """
    ApiMarginV1CrossOrderBatchPlaceOrder unit test stubs
        batchPlaceOrder  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def testApi(self):
        configuration = ApiTestMixin.get_default_configuration()
        # Enter a context with an instance of the API client
        with bitget.ApiClient(configuration) as api_client:
            # Create an instance of the API class
            from bitget.apis.tags import margin_cross_order_api
            api_instance = margin_cross_order_api.MarginCrossBatchPlaceOrder(api_client)
            try:
                from bitget.model.margin_batch_orders_request import MarginBatchOrdersRequest
                from bitget.model.margin_order_request import MarginOrderRequest
                item = MarginOrderRequest(
                    symbol="BTCUSDT",
                    side="buy",
                    orderType="market",
                    timeInForce="gtc",
                    quoteAmount="10",
                    loanType="normal"
                )

                req = MarginBatchOrdersRequest(
                    symbol="BTCUSDT",
                    orderList=[item]
                )

                api_response = api_instance.margin_cross_batch_place_order(req)
                print(api_response)
                self.assertIsNotNone(api_response)
                self.assertIsNotNone(api_response.body)
                self.assertEqual(api_response.body['code'], '00000')
                self.assertEqual(api_response.body['msg'], 'success')
                self.assertIsNotNone(api_response.body['data']['resultList'])
                self.assertIsNotNone(api_response.body['data']['resultList'][0])

            except bitget.ApiException as e:
                print("Exception when calling place_order: %s\n" % e)

    response_status = 200


if __name__ == '__main__':
    unittest.main()
