<?php
/**
 * OrderHistoryResult
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bitget
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bitget Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bitget\Model;

use \ArrayAccess;
use \Bitget\ObjectSerializer;

/**
 * OrderHistoryResult Class Doc Comment
 *
 * @category Class
 * @package  Bitget
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrderHistoryResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderHistoryResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'buy_left_token_id' => 'string',
        'buy_price' => 'string',
        'buy_right_token_id' => 'string',
        'buy_time' => 'string',
        'deal_count' => 'string',
        'net_profit' => 'string',
        'profit' => 'string',
        'profit_rate' => 'string',
        'sell_price' => 'string',
        'sell_time' => 'string',
        'symbol_display_name' => 'string',
        'symbol_id' => 'string',
        'tracking_no' => 'string',
        'trader_user_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'buy_left_token_id' => null,
        'buy_price' => null,
        'buy_right_token_id' => null,
        'buy_time' => null,
        'deal_count' => null,
        'net_profit' => null,
        'profit' => null,
        'profit_rate' => null,
        'sell_price' => null,
        'sell_time' => null,
        'symbol_display_name' => null,
        'symbol_id' => null,
        'tracking_no' => null,
        'trader_user_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'buy_left_token_id' => false,
		'buy_price' => false,
		'buy_right_token_id' => false,
		'buy_time' => false,
		'deal_count' => false,
		'net_profit' => false,
		'profit' => false,
		'profit_rate' => false,
		'sell_price' => false,
		'sell_time' => false,
		'symbol_display_name' => false,
		'symbol_id' => false,
		'tracking_no' => false,
		'trader_user_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'buy_left_token_id' => 'buyLeftTokenId',
        'buy_price' => 'buyPrice',
        'buy_right_token_id' => 'buyRightTokenId',
        'buy_time' => 'buyTime',
        'deal_count' => 'dealCount',
        'net_profit' => 'netProfit',
        'profit' => 'profit',
        'profit_rate' => 'profitRate',
        'sell_price' => 'sellPrice',
        'sell_time' => 'sellTime',
        'symbol_display_name' => 'symbolDisplayName',
        'symbol_id' => 'symbolId',
        'tracking_no' => 'trackingNo',
        'trader_user_id' => 'traderUserId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'buy_left_token_id' => 'setBuyLeftTokenId',
        'buy_price' => 'setBuyPrice',
        'buy_right_token_id' => 'setBuyRightTokenId',
        'buy_time' => 'setBuyTime',
        'deal_count' => 'setDealCount',
        'net_profit' => 'setNetProfit',
        'profit' => 'setProfit',
        'profit_rate' => 'setProfitRate',
        'sell_price' => 'setSellPrice',
        'sell_time' => 'setSellTime',
        'symbol_display_name' => 'setSymbolDisplayName',
        'symbol_id' => 'setSymbolId',
        'tracking_no' => 'setTrackingNo',
        'trader_user_id' => 'setTraderUserId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'buy_left_token_id' => 'getBuyLeftTokenId',
        'buy_price' => 'getBuyPrice',
        'buy_right_token_id' => 'getBuyRightTokenId',
        'buy_time' => 'getBuyTime',
        'deal_count' => 'getDealCount',
        'net_profit' => 'getNetProfit',
        'profit' => 'getProfit',
        'profit_rate' => 'getProfitRate',
        'sell_price' => 'getSellPrice',
        'sell_time' => 'getSellTime',
        'symbol_display_name' => 'getSymbolDisplayName',
        'symbol_id' => 'getSymbolId',
        'tracking_no' => 'getTrackingNo',
        'trader_user_id' => 'getTraderUserId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('buy_left_token_id', $data ?? [], null);
        $this->setIfExists('buy_price', $data ?? [], null);
        $this->setIfExists('buy_right_token_id', $data ?? [], null);
        $this->setIfExists('buy_time', $data ?? [], null);
        $this->setIfExists('deal_count', $data ?? [], null);
        $this->setIfExists('net_profit', $data ?? [], null);
        $this->setIfExists('profit', $data ?? [], null);
        $this->setIfExists('profit_rate', $data ?? [], null);
        $this->setIfExists('sell_price', $data ?? [], null);
        $this->setIfExists('sell_time', $data ?? [], null);
        $this->setIfExists('symbol_display_name', $data ?? [], null);
        $this->setIfExists('symbol_id', $data ?? [], null);
        $this->setIfExists('tracking_no', $data ?? [], null);
        $this->setIfExists('trader_user_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets buy_left_token_id
     *
     * @return string|null
     */
    public function getBuyLeftTokenId()
    {
        return $this->container['buy_left_token_id'];
    }

    /**
     * Sets buy_left_token_id
     *
     * @param string|null $buy_left_token_id buy_left_token_id
     *
     * @return self
     */
    public function setBuyLeftTokenId($buy_left_token_id)
    {

        if (is_null($buy_left_token_id)) {
            throw new \InvalidArgumentException('non-nullable buy_left_token_id cannot be null');
        }

        $this->container['buy_left_token_id'] = $buy_left_token_id;

        return $this;
    }

    /**
     * Gets buy_price
     *
     * @return string|null
     */
    public function getBuyPrice()
    {
        return $this->container['buy_price'];
    }

    /**
     * Sets buy_price
     *
     * @param string|null $buy_price buy_price
     *
     * @return self
     */
    public function setBuyPrice($buy_price)
    {

        if (is_null($buy_price)) {
            throw new \InvalidArgumentException('non-nullable buy_price cannot be null');
        }

        $this->container['buy_price'] = $buy_price;

        return $this;
    }

    /**
     * Gets buy_right_token_id
     *
     * @return string|null
     */
    public function getBuyRightTokenId()
    {
        return $this->container['buy_right_token_id'];
    }

    /**
     * Sets buy_right_token_id
     *
     * @param string|null $buy_right_token_id buy_right_token_id
     *
     * @return self
     */
    public function setBuyRightTokenId($buy_right_token_id)
    {

        if (is_null($buy_right_token_id)) {
            throw new \InvalidArgumentException('non-nullable buy_right_token_id cannot be null');
        }

        $this->container['buy_right_token_id'] = $buy_right_token_id;

        return $this;
    }

    /**
     * Gets buy_time
     *
     * @return string|null
     */
    public function getBuyTime()
    {
        return $this->container['buy_time'];
    }

    /**
     * Sets buy_time
     *
     * @param string|null $buy_time buy_time
     *
     * @return self
     */
    public function setBuyTime($buy_time)
    {

        if (is_null($buy_time)) {
            throw new \InvalidArgumentException('non-nullable buy_time cannot be null');
        }

        $this->container['buy_time'] = $buy_time;

        return $this;
    }

    /**
     * Gets deal_count
     *
     * @return string|null
     */
    public function getDealCount()
    {
        return $this->container['deal_count'];
    }

    /**
     * Sets deal_count
     *
     * @param string|null $deal_count deal_count
     *
     * @return self
     */
    public function setDealCount($deal_count)
    {

        if (is_null($deal_count)) {
            throw new \InvalidArgumentException('non-nullable deal_count cannot be null');
        }

        $this->container['deal_count'] = $deal_count;

        return $this;
    }

    /**
     * Gets net_profit
     *
     * @return string|null
     */
    public function getNetProfit()
    {
        return $this->container['net_profit'];
    }

    /**
     * Sets net_profit
     *
     * @param string|null $net_profit net_profit
     *
     * @return self
     */
    public function setNetProfit($net_profit)
    {

        if (is_null($net_profit)) {
            throw new \InvalidArgumentException('non-nullable net_profit cannot be null');
        }

        $this->container['net_profit'] = $net_profit;

        return $this;
    }

    /**
     * Gets profit
     *
     * @return string|null
     */
    public function getProfit()
    {
        return $this->container['profit'];
    }

    /**
     * Sets profit
     *
     * @param string|null $profit profit
     *
     * @return self
     */
    public function setProfit($profit)
    {

        if (is_null($profit)) {
            throw new \InvalidArgumentException('non-nullable profit cannot be null');
        }

        $this->container['profit'] = $profit;

        return $this;
    }

    /**
     * Gets profit_rate
     *
     * @return string|null
     */
    public function getProfitRate()
    {
        return $this->container['profit_rate'];
    }

    /**
     * Sets profit_rate
     *
     * @param string|null $profit_rate profit_rate
     *
     * @return self
     */
    public function setProfitRate($profit_rate)
    {

        if (is_null($profit_rate)) {
            throw new \InvalidArgumentException('non-nullable profit_rate cannot be null');
        }

        $this->container['profit_rate'] = $profit_rate;

        return $this;
    }

    /**
     * Gets sell_price
     *
     * @return string|null
     */
    public function getSellPrice()
    {
        return $this->container['sell_price'];
    }

    /**
     * Sets sell_price
     *
     * @param string|null $sell_price sell_price
     *
     * @return self
     */
    public function setSellPrice($sell_price)
    {

        if (is_null($sell_price)) {
            throw new \InvalidArgumentException('non-nullable sell_price cannot be null');
        }

        $this->container['sell_price'] = $sell_price;

        return $this;
    }

    /**
     * Gets sell_time
     *
     * @return string|null
     */
    public function getSellTime()
    {
        return $this->container['sell_time'];
    }

    /**
     * Sets sell_time
     *
     * @param string|null $sell_time sell_time
     *
     * @return self
     */
    public function setSellTime($sell_time)
    {

        if (is_null($sell_time)) {
            throw new \InvalidArgumentException('non-nullable sell_time cannot be null');
        }

        $this->container['sell_time'] = $sell_time;

        return $this;
    }

    /**
     * Gets symbol_display_name
     *
     * @return string|null
     */
    public function getSymbolDisplayName()
    {
        return $this->container['symbol_display_name'];
    }

    /**
     * Sets symbol_display_name
     *
     * @param string|null $symbol_display_name symbol_display_name
     *
     * @return self
     */
    public function setSymbolDisplayName($symbol_display_name)
    {

        if (is_null($symbol_display_name)) {
            throw new \InvalidArgumentException('non-nullable symbol_display_name cannot be null');
        }

        $this->container['symbol_display_name'] = $symbol_display_name;

        return $this;
    }

    /**
     * Gets symbol_id
     *
     * @return string|null
     */
    public function getSymbolId()
    {
        return $this->container['symbol_id'];
    }

    /**
     * Sets symbol_id
     *
     * @param string|null $symbol_id symbol_id
     *
     * @return self
     */
    public function setSymbolId($symbol_id)
    {

        if (is_null($symbol_id)) {
            throw new \InvalidArgumentException('non-nullable symbol_id cannot be null');
        }

        $this->container['symbol_id'] = $symbol_id;

        return $this;
    }

    /**
     * Gets tracking_no
     *
     * @return string|null
     */
    public function getTrackingNo()
    {
        return $this->container['tracking_no'];
    }

    /**
     * Sets tracking_no
     *
     * @param string|null $tracking_no tracking_no
     *
     * @return self
     */
    public function setTrackingNo($tracking_no)
    {

        if (is_null($tracking_no)) {
            throw new \InvalidArgumentException('non-nullable tracking_no cannot be null');
        }

        $this->container['tracking_no'] = $tracking_no;

        return $this;
    }

    /**
     * Gets trader_user_id
     *
     * @return string|null
     */
    public function getTraderUserId()
    {
        return $this->container['trader_user_id'];
    }

    /**
     * Sets trader_user_id
     *
     * @param string|null $trader_user_id trader_user_id
     *
     * @return self
     */
    public function setTraderUserId($trader_user_id)
    {

        if (is_null($trader_user_id)) {
            throw new \InvalidArgumentException('non-nullable trader_user_id cannot be null');
        }

        $this->container['trader_user_id'] = $trader_user_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


