<?php
/**
 * TraderSettingResult
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bitget
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bitget Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bitget\Model;

use \ArrayAccess;
use \Bitget\ObjectSerializer;

/**
 * TraderSettingResult Class Doc Comment
 *
 * @category Class
 * @package  Bitget
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TraderSettingResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TraderSettingResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'labels' => '\Bitget\Model\TraderSettingLablesResult[]',
        'open_product' => 'bool',
        'show_assets_map' => 'bool',
        'show_equity' => 'bool',
        'support_product_codes' => '\Bitget\Model\TraderSettingSupportProductResult[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'labels' => null,
        'open_product' => null,
        'show_assets_map' => null,
        'show_equity' => null,
        'support_product_codes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'labels' => false,
		'open_product' => false,
		'show_assets_map' => false,
		'show_equity' => false,
		'support_product_codes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'labels' => 'labels',
        'open_product' => 'openProduct',
        'show_assets_map' => 'showAssetsMap',
        'show_equity' => 'showEquity',
        'support_product_codes' => 'supportProductCodes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'labels' => 'setLabels',
        'open_product' => 'setOpenProduct',
        'show_assets_map' => 'setShowAssetsMap',
        'show_equity' => 'setShowEquity',
        'support_product_codes' => 'setSupportProductCodes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'labels' => 'getLabels',
        'open_product' => 'getOpenProduct',
        'show_assets_map' => 'getShowAssetsMap',
        'show_equity' => 'getShowEquity',
        'support_product_codes' => 'getSupportProductCodes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('labels', $data ?? [], null);
        $this->setIfExists('open_product', $data ?? [], null);
        $this->setIfExists('show_assets_map', $data ?? [], null);
        $this->setIfExists('show_equity', $data ?? [], null);
        $this->setIfExists('support_product_codes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets labels
     *
     * @return \Bitget\Model\TraderSettingLablesResult[]|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \Bitget\Model\TraderSettingLablesResult[]|null $labels labels
     *
     * @return self
     */
    public function setLabels($labels)
    {

        if (is_null($labels)) {
            throw new \InvalidArgumentException('non-nullable labels cannot be null');
        }

        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets open_product
     *
     * @return bool|null
     */
    public function getOpenProduct()
    {
        return $this->container['open_product'];
    }

    /**
     * Sets open_product
     *
     * @param bool|null $open_product open_product
     *
     * @return self
     */
    public function setOpenProduct($open_product)
    {

        if (is_null($open_product)) {
            throw new \InvalidArgumentException('non-nullable open_product cannot be null');
        }

        $this->container['open_product'] = $open_product;

        return $this;
    }

    /**
     * Gets show_assets_map
     *
     * @return bool|null
     */
    public function getShowAssetsMap()
    {
        return $this->container['show_assets_map'];
    }

    /**
     * Sets show_assets_map
     *
     * @param bool|null $show_assets_map show_assets_map
     *
     * @return self
     */
    public function setShowAssetsMap($show_assets_map)
    {

        if (is_null($show_assets_map)) {
            throw new \InvalidArgumentException('non-nullable show_assets_map cannot be null');
        }

        $this->container['show_assets_map'] = $show_assets_map;

        return $this;
    }

    /**
     * Gets show_equity
     *
     * @return bool|null
     */
    public function getShowEquity()
    {
        return $this->container['show_equity'];
    }

    /**
     * Sets show_equity
     *
     * @param bool|null $show_equity show_equity
     *
     * @return self
     */
    public function setShowEquity($show_equity)
    {

        if (is_null($show_equity)) {
            throw new \InvalidArgumentException('non-nullable show_equity cannot be null');
        }

        $this->container['show_equity'] = $show_equity;

        return $this;
    }

    /**
     * Gets support_product_codes
     *
     * @return \Bitget\Model\TraderSettingSupportProductResult[]|null
     */
    public function getSupportProductCodes()
    {
        return $this->container['support_product_codes'];
    }

    /**
     * Sets support_product_codes
     *
     * @param \Bitget\Model\TraderSettingSupportProductResult[]|null $support_product_codes support_product_codes
     *
     * @return self
     */
    public function setSupportProductCodes($support_product_codes)
    {

        if (is_null($support_product_codes)) {
            throw new \InvalidArgumentException('non-nullable support_product_codes cannot be null');
        }

        $this->container['support_product_codes'] = $support_product_codes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


