# coding: utf-8

# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from bitget.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from bitget.model.api_response_result_of_list_of_margin_cross_assets_population_result import ApiResponseResultOfListOfMarginCrossAssetsPopulationResult
from bitget.model.api_response_result_of_list_of_margin_cross_level_result import ApiResponseResultOfListOfMarginCrossLevelResult
from bitget.model.api_response_result_of_list_of_margin_cross_rate_and_limit_result import ApiResponseResultOfListOfMarginCrossRateAndLimitResult
from bitget.model.api_response_result_of_list_of_margin_isolated_assets_population_result import ApiResponseResultOfListOfMarginIsolatedAssetsPopulationResult
from bitget.model.api_response_result_of_list_of_margin_isolated_assets_risk_result import ApiResponseResultOfListOfMarginIsolatedAssetsRiskResult
from bitget.model.api_response_result_of_list_of_margin_isolated_level_result import ApiResponseResultOfListOfMarginIsolatedLevelResult
from bitget.model.api_response_result_of_list_of_margin_isolated_rate_and_limit_result import ApiResponseResultOfListOfMarginIsolatedRateAndLimitResult
from bitget.model.api_response_result_of_list_of_margin_system_result import ApiResponseResultOfListOfMarginSystemResult
from bitget.model.api_response_result_of_margin_batch_cancel_order_result import ApiResponseResultOfMarginBatchCancelOrderResult
from bitget.model.api_response_result_of_margin_batch_place_order_result import ApiResponseResultOfMarginBatchPlaceOrderResult
from bitget.model.api_response_result_of_margin_cross_assets_result import ApiResponseResultOfMarginCrossAssetsResult
from bitget.model.api_response_result_of_margin_cross_assets_risk_result import ApiResponseResultOfMarginCrossAssetsRiskResult
from bitget.model.api_response_result_of_margin_cross_borrow_limit_result import ApiResponseResultOfMarginCrossBorrowLimitResult
from bitget.model.api_response_result_of_margin_cross_fin_flow_result import ApiResponseResultOfMarginCrossFinFlowResult
from bitget.model.api_response_result_of_margin_cross_max_borrow_result import ApiResponseResultOfMarginCrossMaxBorrowResult
from bitget.model.api_response_result_of_margin_cross_repay_result import ApiResponseResultOfMarginCrossRepayResult
from bitget.model.api_response_result_of_margin_interest_info_result import ApiResponseResultOfMarginInterestInfoResult
from bitget.model.api_response_result_of_margin_isolated_assets_result import ApiResponseResultOfMarginIsolatedAssetsResult
from bitget.model.api_response_result_of_margin_isolated_borrow_limit_result import ApiResponseResultOfMarginIsolatedBorrowLimitResult
from bitget.model.api_response_result_of_margin_isolated_fin_flow_result import ApiResponseResultOfMarginIsolatedFinFlowResult
from bitget.model.api_response_result_of_margin_isolated_interest_info_result import ApiResponseResultOfMarginIsolatedInterestInfoResult
from bitget.model.api_response_result_of_margin_isolated_liquidation_info_result import ApiResponseResultOfMarginIsolatedLiquidationInfoResult
from bitget.model.api_response_result_of_margin_isolated_loan_info_result import ApiResponseResultOfMarginIsolatedLoanInfoResult
from bitget.model.api_response_result_of_margin_isolated_max_borrow_result import ApiResponseResultOfMarginIsolatedMaxBorrowResult
from bitget.model.api_response_result_of_margin_isolated_repay_info_result import ApiResponseResultOfMarginIsolatedRepayInfoResult
from bitget.model.api_response_result_of_margin_isolated_repay_result import ApiResponseResultOfMarginIsolatedRepayResult
from bitget.model.api_response_result_of_margin_liquidation_info_result import ApiResponseResultOfMarginLiquidationInfoResult
from bitget.model.api_response_result_of_margin_loan_info_result import ApiResponseResultOfMarginLoanInfoResult
from bitget.model.api_response_result_of_margin_open_order_info_result import ApiResponseResultOfMarginOpenOrderInfoResult
from bitget.model.api_response_result_of_margin_place_order_result import ApiResponseResultOfMarginPlaceOrderResult
from bitget.model.api_response_result_of_margin_repay_info_result import ApiResponseResultOfMarginRepayInfoResult
from bitget.model.api_response_result_of_margin_trade_detail_info_result import ApiResponseResultOfMarginTradeDetailInfoResult
from bitget.model.api_response_result_of_merchant_adv_result import ApiResponseResultOfMerchantAdvResult
from bitget.model.api_response_result_of_merchant_info_result import ApiResponseResultOfMerchantInfoResult
from bitget.model.api_response_result_of_merchant_order_result import ApiResponseResultOfMerchantOrderResult
from bitget.model.api_response_result_of_merchant_person_info import ApiResponseResultOfMerchantPersonInfo
from bitget.model.api_response_result_of_void import ApiResponseResultOfVoid
from bitget.model.fiat_payment_detail_info import FiatPaymentDetailInfo
from bitget.model.fiat_payment_info import FiatPaymentInfo
from bitget.model.margin_batch_cancel_order_request import MarginBatchCancelOrderRequest
from bitget.model.margin_batch_cancel_order_result import MarginBatchCancelOrderResult
from bitget.model.margin_batch_orders_request import MarginBatchOrdersRequest
from bitget.model.margin_batch_place_order_failure_result import MarginBatchPlaceOrderFailureResult
from bitget.model.margin_batch_place_order_result import MarginBatchPlaceOrderResult
from bitget.model.margin_cancel_order_failure_result import MarginCancelOrderFailureResult
from bitget.model.margin_cancel_order_request import MarginCancelOrderRequest
from bitget.model.margin_cancel_order_result import MarginCancelOrderResult
from bitget.model.margin_cross_assets_population_result import MarginCrossAssetsPopulationResult
from bitget.model.margin_cross_assets_result import MarginCrossAssetsResult
from bitget.model.margin_cross_assets_risk_result import MarginCrossAssetsRiskResult
from bitget.model.margin_cross_borrow_limit_result import MarginCrossBorrowLimitResult
from bitget.model.margin_cross_fin_flow_info import MarginCrossFinFlowInfo
from bitget.model.margin_cross_fin_flow_result import MarginCrossFinFlowResult
from bitget.model.margin_cross_level_result import MarginCrossLevelResult
from bitget.model.margin_cross_limit_request import MarginCrossLimitRequest
from bitget.model.margin_cross_max_borrow_request import MarginCrossMaxBorrowRequest
from bitget.model.margin_cross_max_borrow_result import MarginCrossMaxBorrowResult
from bitget.model.margin_cross_rate_and_limit_result import MarginCrossRateAndLimitResult
from bitget.model.margin_cross_repay_request import MarginCrossRepayRequest
from bitget.model.margin_cross_repay_result import MarginCrossRepayResult
from bitget.model.margin_cross_vip_result import MarginCrossVipResult
from bitget.model.margin_interest_info import MarginInterestInfo
from bitget.model.margin_interest_info_result import MarginInterestInfoResult
from bitget.model.margin_isolated_assets_population_result import MarginIsolatedAssetsPopulationResult
from bitget.model.margin_isolated_assets_result import MarginIsolatedAssetsResult
from bitget.model.margin_isolated_assets_risk_request import MarginIsolatedAssetsRiskRequest
from bitget.model.margin_isolated_assets_risk_result import MarginIsolatedAssetsRiskResult
from bitget.model.margin_isolated_borrow_limit_result import MarginIsolatedBorrowLimitResult
from bitget.model.margin_isolated_fin_flow_info import MarginIsolatedFinFlowInfo
from bitget.model.margin_isolated_fin_flow_result import MarginIsolatedFinFlowResult
from bitget.model.margin_isolated_interest_info import MarginIsolatedInterestInfo
from bitget.model.margin_isolated_interest_info_result import MarginIsolatedInterestInfoResult
from bitget.model.margin_isolated_level_result import MarginIsolatedLevelResult
from bitget.model.margin_isolated_limit_request import MarginIsolatedLimitRequest
from bitget.model.margin_isolated_liquidation_info import MarginIsolatedLiquidationInfo
from bitget.model.margin_isolated_liquidation_info_result import MarginIsolatedLiquidationInfoResult
from bitget.model.margin_isolated_loan_info import MarginIsolatedLoanInfo
from bitget.model.margin_isolated_loan_info_result import MarginIsolatedLoanInfoResult
from bitget.model.margin_isolated_max_borrow_request import MarginIsolatedMaxBorrowRequest
from bitget.model.margin_isolated_max_borrow_result import MarginIsolatedMaxBorrowResult
from bitget.model.margin_isolated_rate_and_limit_result import MarginIsolatedRateAndLimitResult
from bitget.model.margin_isolated_repay_info import MarginIsolatedRepayInfo
from bitget.model.margin_isolated_repay_info_result import MarginIsolatedRepayInfoResult
from bitget.model.margin_isolated_repay_request import MarginIsolatedRepayRequest
from bitget.model.margin_isolated_repay_result import MarginIsolatedRepayResult
from bitget.model.margin_isolated_vip_result import MarginIsolatedVipResult
from bitget.model.margin_liquidation_info import MarginLiquidationInfo
from bitget.model.margin_liquidation_info_result import MarginLiquidationInfoResult
from bitget.model.margin_loan_info import MarginLoanInfo
from bitget.model.margin_loan_info_result import MarginLoanInfoResult
from bitget.model.margin_open_order_info_result import MarginOpenOrderInfoResult
from bitget.model.margin_order_info import MarginOrderInfo
from bitget.model.margin_order_request import MarginOrderRequest
from bitget.model.margin_place_order_result import MarginPlaceOrderResult
from bitget.model.margin_repay_info import MarginRepayInfo
from bitget.model.margin_repay_info_result import MarginRepayInfoResult
from bitget.model.margin_system_result import MarginSystemResult
from bitget.model.margin_trade_detail_info import MarginTradeDetailInfo
from bitget.model.margin_trade_detail_info_result import MarginTradeDetailInfoResult
from bitget.model.merchant_adv_info import MerchantAdvInfo
from bitget.model.merchant_adv_result import MerchantAdvResult
from bitget.model.merchant_adv_user_limit_info import MerchantAdvUserLimitInfo
from bitget.model.merchant_info import MerchantInfo
from bitget.model.merchant_info_result import MerchantInfoResult
from bitget.model.merchant_order_info import MerchantOrderInfo
from bitget.model.merchant_order_payment_info import MerchantOrderPaymentInfo
from bitget.model.merchant_order_result import MerchantOrderResult
from bitget.model.merchant_person_info import MerchantPersonInfo
from bitget.model.order_payment_detail_info import OrderPaymentDetailInfo
