<?php
/**
 * MarginIsolatedLiquidationInfoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bitget
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bitget Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bitget\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MarginIsolatedLiquidationInfoTest Class Doc Comment
 *
 * @category    Class
 * @description MarginIsolatedLiquidationInfo
 * @package     Bitget
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MarginIsolatedLiquidationInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MarginIsolatedLiquidationInfo"
     */
    public function testMarginIsolatedLiquidationInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ctime"
     */
    public function testPropertyCtime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liq_end_time"
     */
    public function testPropertyLiqEndTime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liq_fee"
     */
    public function testPropertyLiqFee()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liq_id"
     */
    public function testPropertyLiqId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liq_risk"
     */
    public function testPropertyLiqRisk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liq_start_time"
     */
    public function testPropertyLiqStartTime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "symbol"
     */
    public function testPropertySymbol()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_assets"
     */
    public function testPropertyTotalAssets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_debt"
     */
    public function testPropertyTotalDebt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
