# coding: utf-8

"""
    Bitget Open API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from bitget.paths.api_margin_v1_cross_account_assets.get import MarginCrossAccountAssets
from bitget.paths.api_margin_v1_cross_account_borrow.post import MarginCrossAccountBorrow
from bitget.paths.api_margin_v1_cross_account_max_borrowable_amount.post import MarginCrossAccountMaxBorrowableAmount
from bitget.paths.api_margin_v1_cross_account_max_transfer_out_amount.get import MarginCrossAccountMaxTransferOutAmount
from bitget.paths.api_margin_v1_cross_account_repay.post import MarginCrossAccountRepay
from bitget.paths.api_margin_v1_cross_account_risk_rate.get import MarginCrossAccountRiskRate
from bitget.paths.api_margin_v1_cross_account_void.get import Void


class MarginCrossAccountApi(
    MarginCrossAccountAssets,
    MarginCrossAccountBorrow,
    MarginCrossAccountMaxBorrowableAmount,
    MarginCrossAccountMaxTransferOutAmount,
    MarginCrossAccountRepay,
    MarginCrossAccountRiskRate,
    Void,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
