/*
 * Bitget Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitget.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MarginIsolatedRepayRequest
 */
public class MarginIsolatedRepayRequestTest {
    private final MarginIsolatedRepayRequest model = new MarginIsolatedRepayRequest();

    /**
     * Model tests for MarginIsolatedRepayRequest
     */
    @Test
    public void testMarginIsolatedRepayRequest() {
        // TODO: test MarginIsolatedRepayRequest
    }

    /**
     * Test the property 'coin'
     */
    @Test
    public void coinTest() {
        // TODO: test coin
    }

    /**
     * Test the property 'repayAmount'
     */
    @Test
    public void repayAmountTest() {
        // TODO: test repayAmount
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

}
