/*
 * Bitget Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitget.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MarginIsolatedLevelResult
 */
public class MarginIsolatedLevelResultTest {
    private final MarginIsolatedLevelResult model = new MarginIsolatedLevelResult();

    /**
     * Model tests for MarginIsolatedLevelResult
     */
    @Test
    public void testMarginIsolatedLevelResult() {
        // TODO: test MarginIsolatedLevelResult
    }

    /**
     * Test the property 'baseCoin'
     */
    @Test
    public void baseCoinTest() {
        // TODO: test baseCoin
    }

    /**
     * Test the property 'baseMaxBorrowableAmount'
     */
    @Test
    public void baseMaxBorrowableAmountTest() {
        // TODO: test baseMaxBorrowableAmount
    }

    /**
     * Test the property 'initRate'
     */
    @Test
    public void initRateTest() {
        // TODO: test initRate
    }

    /**
     * Test the property 'leverage'
     */
    @Test
    public void leverageTest() {
        // TODO: test leverage
    }

    /**
     * Test the property 'maintainMarginRate'
     */
    @Test
    public void maintainMarginRateTest() {
        // TODO: test maintainMarginRate
    }

    /**
     * Test the property 'quoteCoin'
     */
    @Test
    public void quoteCoinTest() {
        // TODO: test quoteCoin
    }

    /**
     * Test the property 'quoteMaxBorrowableAmount'
     */
    @Test
    public void quoteMaxBorrowableAmountTest() {
        // TODO: test quoteMaxBorrowableAmount
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'tier'
     */
    @Test
    public void tierTest() {
        // TODO: test tier
    }

}
