/*
 * Bitget Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitget.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MarginIsolatedFinFlowInfo
 */
public class MarginIsolatedFinFlowInfoTest {
    private final MarginIsolatedFinFlowInfo model = new MarginIsolatedFinFlowInfo();

    /**
     * Model tests for MarginIsolatedFinFlowInfo
     */
    @Test
    public void testMarginIsolatedFinFlowInfo() {
        // TODO: test MarginIsolatedFinFlowInfo
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'coin'
     */
    @Test
    public void coinTest() {
        // TODO: test coin
    }

    /**
     * Test the property 'ctime'
     */
    @Test
    public void ctimeTest() {
        // TODO: test ctime
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'marginId'
     */
    @Test
    public void marginIdTest() {
        // TODO: test marginId
    }

    /**
     * Test the property 'marginType'
     */
    @Test
    public void marginTypeTest() {
        // TODO: test marginType
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

}
