/*
 * Bitget Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitget.openapi.api;

import com.bitget.openapi.ApiConfig;
import com.bitget.openapi.ApiException;
import com.bitget.openapi.model.ApiResponseResultOfMarginRepayInfoResult;
import com.bitget.openapi.model.ApiResponseResultOfVoid;
import com.bitget.openapi.model.MarginIsolatedRepayInfo;
import com.bitget.openapi.model.MarginRepayInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * API tests for MarginCrossRepayApi
 */
public class MarginCrossRepayApiTest {

    private final MarginCrossRepayApi api = new MarginCrossRepayApi(ApiConfig.getConfig());

    /**
     * list
     *
     * Get liquidation List
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void repayListTest() throws ApiException {
        String startTime = "1677274167003";
        String endTime = "1680057356760";
        String pageSize = "10";
        String coin = null;
        String repayId = null;
        String pageId = null;
        ApiResponseResultOfMarginRepayInfoResult response = api.repayList(startTime, coin, repayId, endTime, pageSize, pageId);
        assertThat(response).isNotNull();
        assertThat(response.getData()).isNotNull();
        if (response.getData().getResultList() != null && response.getData().getResultList().size() > 0) {
            for(MarginRepayInfo item : response.getData().getResultList()) {
                assertThat(item.getCoin()).isNotBlank();
                assertThat(item.getAmount()).isNotBlank();
                assertThat(item.getType()).isNotBlank();
                assertThat(item.getRepayId()).isNotBlank();
                assertThat(item.getInterest()).isNotBlank();
                assertThat(item.getTotalAmount()).isNotBlank();
            }
        }
    }

}
