/**
 * Bitget Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MarginOrderInfo {
    'baseQuantity'?: string;
    'clientOid'?: string;
    'ctime'?: string;
    'fillPrice'?: string;
    'fillQuantity'?: string;
    'fillTotalAmount'?: string;
    'loanType'?: string;
    'orderId'?: string;
    'orderType'?: string;
    'price'?: string;
    'quoteAmount'?: string;
    'side'?: string;
    'source'?: string;
    'status'?: string;
    'symbol'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "baseQuantity",
            "baseName": "baseQuantity",
            "type": "string"
        },
        {
            "name": "clientOid",
            "baseName": "clientOid",
            "type": "string"
        },
        {
            "name": "ctime",
            "baseName": "ctime",
            "type": "string"
        },
        {
            "name": "fillPrice",
            "baseName": "fillPrice",
            "type": "string"
        },
        {
            "name": "fillQuantity",
            "baseName": "fillQuantity",
            "type": "string"
        },
        {
            "name": "fillTotalAmount",
            "baseName": "fillTotalAmount",
            "type": "string"
        },
        {
            "name": "loanType",
            "baseName": "loanType",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string"
        },
        {
            "name": "orderType",
            "baseName": "orderType",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "quoteAmount",
            "baseName": "quoteAmount",
            "type": "string"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MarginOrderInfo.attributeTypeMap;
    }
}

