/**
 * Bitget Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrderCurrentResult {
    'buyDelegateCount'?: string;
    'buyPrice'?: string;
    'buyTime'?: string;
    'dealCount'?: string;
    'holdCount'?: string;
    'profit'?: string;
    'profitRate'?: string;
    'stopLossPrice'?: string;
    'stopProfitPrice'?: string;
    'symbolDisplayName'?: string;
    'symbolId'?: string;
    'trackingNo'?: string;
    'trackingType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buyDelegateCount",
            "baseName": "buyDelegateCount",
            "type": "string"
        },
        {
            "name": "buyPrice",
            "baseName": "buyPrice",
            "type": "string"
        },
        {
            "name": "buyTime",
            "baseName": "buyTime",
            "type": "string"
        },
        {
            "name": "dealCount",
            "baseName": "dealCount",
            "type": "string"
        },
        {
            "name": "holdCount",
            "baseName": "holdCount",
            "type": "string"
        },
        {
            "name": "profit",
            "baseName": "profit",
            "type": "string"
        },
        {
            "name": "profitRate",
            "baseName": "profitRate",
            "type": "string"
        },
        {
            "name": "stopLossPrice",
            "baseName": "stopLossPrice",
            "type": "string"
        },
        {
            "name": "stopProfitPrice",
            "baseName": "stopProfitPrice",
            "type": "string"
        },
        {
            "name": "symbolDisplayName",
            "baseName": "symbolDisplayName",
            "type": "string"
        },
        {
            "name": "symbolId",
            "baseName": "symbolId",
            "type": "string"
        },
        {
            "name": "trackingNo",
            "baseName": "trackingNo",
            "type": "string"
        },
        {
            "name": "trackingType",
            "baseName": "trackingType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrderCurrentResult.attributeTypeMap;
    }
}

