# coding: utf-8

"""
    Bitget Open API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import bitget
from bitget.model.fiat_payment_detail_info import FiatPaymentDetailInfo
from bitget import configuration


class TestFiatPaymentDetailInfo(unittest.TestCase):
    """FiatPaymentDetailInfo unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
