# coding: utf-8

"""
    Bitget Open API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import bitget
from bitget.model.wait_profit_detail_list_request import WaitProfitDetailListRequest
from bitget import configuration


class TestWaitProfitDetailListRequest(unittest.TestCase):
    """WaitProfitDetailListRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
