# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from bitget.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    API_MARGIN_V1_CROSS_ACCOUNT_ASSETS = "/api/margin/v1/cross/account/assets"
    API_MARGIN_V1_CROSS_ACCOUNT_BORROW = "/api/margin/v1/cross/account/borrow"
    API_MARGIN_V1_CROSS_ACCOUNT_MAX_BORROWABLE_AMOUNT = "/api/margin/v1/cross/account/maxBorrowableAmount"
    API_MARGIN_V1_CROSS_ACCOUNT_MAX_TRANSFER_OUT_AMOUNT = "/api/margin/v1/cross/account/maxTransferOutAmount"
    API_MARGIN_V1_CROSS_ACCOUNT_REPAY = "/api/margin/v1/cross/account/repay"
    API_MARGIN_V1_CROSS_ACCOUNT_RISK_RATE = "/api/margin/v1/cross/account/riskRate"
    API_MARGIN_V1_CROSS_ACCOUNT_VOID = "/api/margin/v1/cross/account/void"
    API_MARGIN_V1_CROSS_FIN_LIST = "/api/margin/v1/cross/fin/list"
    API_MARGIN_V1_CROSS_INTEREST_LIST = "/api/margin/v1/cross/interest/list"
    API_MARGIN_V1_CROSS_LIQUIDATION_LIST = "/api/margin/v1/cross/liquidation/list"
    API_MARGIN_V1_CROSS_LOAN_LIST = "/api/margin/v1/cross/loan/list"
    API_MARGIN_V1_CROSS_ORDER_BATCH_CANCEL_ORDER = "/api/margin/v1/cross/order/batchCancelOrder"
    API_MARGIN_V1_CROSS_ORDER_BATCH_PLACE_ORDER = "/api/margin/v1/cross/order/batchPlaceOrder"
    API_MARGIN_V1_CROSS_ORDER_CANCEL_ORDER = "/api/margin/v1/cross/order/cancelOrder"
    API_MARGIN_V1_CROSS_ORDER_FILLS = "/api/margin/v1/cross/order/fills"
    API_MARGIN_V1_CROSS_ORDER_HISTORY = "/api/margin/v1/cross/order/history"
    API_MARGIN_V1_CROSS_ORDER_OPEN_ORDERS = "/api/margin/v1/cross/order/openOrders"
    API_MARGIN_V1_CROSS_ORDER_PLACE_ORDER = "/api/margin/v1/cross/order/placeOrder"
    API_MARGIN_V1_CROSS_PUBLIC_INTEREST_RATE_AND_LIMIT = "/api/margin/v1/cross/public/interestRateAndLimit"
    API_MARGIN_V1_CROSS_PUBLIC_TIER_DATA = "/api/margin/v1/cross/public/tierData"
    API_MARGIN_V1_CROSS_REPAY_LIST = "/api/margin/v1/cross/repay/list"
    API_MARGIN_V1_ISOLATED_ACCOUNT_ASSETS = "/api/margin/v1/isolated/account/assets"
    API_MARGIN_V1_ISOLATED_ACCOUNT_BORROW = "/api/margin/v1/isolated/account/borrow"
    API_MARGIN_V1_ISOLATED_ACCOUNT_MAX_BORROWABLE_AMOUNT = "/api/margin/v1/isolated/account/maxBorrowableAmount"
    API_MARGIN_V1_ISOLATED_ACCOUNT_MAX_TRANSFER_OUT_AMOUNT = "/api/margin/v1/isolated/account/maxTransferOutAmount"
    API_MARGIN_V1_ISOLATED_ACCOUNT_REPAY = "/api/margin/v1/isolated/account/repay"
    API_MARGIN_V1_ISOLATED_ACCOUNT_RISK_RATE = "/api/margin/v1/isolated/account/riskRate"
    API_MARGIN_V1_ISOLATED_FIN_LIST = "/api/margin/v1/isolated/fin/list"
    API_MARGIN_V1_ISOLATED_INTEREST_LIST = "/api/margin/v1/isolated/interest/list"
    API_MARGIN_V1_ISOLATED_LIQUIDATION_LIST = "/api/margin/v1/isolated/liquidation/list"
    API_MARGIN_V1_ISOLATED_LOAN_LIST = "/api/margin/v1/isolated/loan/list"
    API_MARGIN_V1_ISOLATED_ORDER_BATCH_CANCEL_ORDER = "/api/margin/v1/isolated/order/batchCancelOrder"
    API_MARGIN_V1_ISOLATED_ORDER_BATCH_PLACE_ORDER = "/api/margin/v1/isolated/order/batchPlaceOrder"
    API_MARGIN_V1_ISOLATED_ORDER_CANCEL_ORDER = "/api/margin/v1/isolated/order/cancelOrder"
    API_MARGIN_V1_ISOLATED_ORDER_FILLS = "/api/margin/v1/isolated/order/fills"
    API_MARGIN_V1_ISOLATED_ORDER_HISTORY = "/api/margin/v1/isolated/order/history"
    API_MARGIN_V1_ISOLATED_ORDER_OPEN_ORDERS = "/api/margin/v1/isolated/order/openOrders"
    API_MARGIN_V1_ISOLATED_ORDER_PLACE_ORDER = "/api/margin/v1/isolated/order/placeOrder"
    API_MARGIN_V1_ISOLATED_PUBLIC_INTEREST_RATE_AND_LIMIT = "/api/margin/v1/isolated/public/interestRateAndLimit"
    API_MARGIN_V1_ISOLATED_PUBLIC_TIER_DATA = "/api/margin/v1/isolated/public/tierData"
    API_MARGIN_V1_ISOLATED_REPAY_LIST = "/api/margin/v1/isolated/repay/list"
    API_MARGIN_V1_PUBLIC_CURRENCIES = "/api/margin/v1/public/currencies"
    API_P2P_V1_MERCHANT_ADV_LIST = "/api/p2p/v1/merchant/advList"
    API_P2P_V1_MERCHANT_MERCHANT_INFO = "/api/p2p/v1/merchant/merchantInfo"
    API_P2P_V1_MERCHANT_MERCHANT_LIST = "/api/p2p/v1/merchant/merchantList"
    API_P2P_V1_MERCHANT_ORDER_LIST = "/api/p2p/v1/merchant/orderList"
    API_SPOT_V1_TRACE_ORDER_CLOSE_TRACKING_ORDER = "/api/spot/v1/trace/order/closeTrackingOrder"
    API_SPOT_V1_TRACE_ORDER_END_ORDER = "/api/spot/v1/trace/order/endOrder"
    API_SPOT_V1_TRACE_ORDER_GET_TRACE_SETTINGS = "/api/spot/v1/trace/order/getTraceSettings"
    API_SPOT_V1_TRACE_ORDER_GET_TRADER_SETTINGS = "/api/spot/v1/trace/order/getTraderSettings"
    API_SPOT_V1_TRACE_ORDER_MY_TRACERS = "/api/spot/v1/trace/order/myTracers"
    API_SPOT_V1_TRACE_ORDER_MY_TRADERS = "/api/spot/v1/trace/order/myTraders"
    API_SPOT_V1_TRACE_ORDER_ORDER_CURRENT_LIST = "/api/spot/v1/trace/order/orderCurrentList"
    API_SPOT_V1_TRACE_ORDER_ORDER_HISTORY_LIST = "/api/spot/v1/trace/order/orderHistoryList"
    API_SPOT_V1_TRACE_ORDER_REMOVE_TRADER = "/api/spot/v1/trace/order/removeTrader"
    API_SPOT_V1_TRACE_ORDER_SET_PRODUCT_CODE = "/api/spot/v1/trace/order/setProductCode"
    API_SPOT_V1_TRACE_ORDER_SET_TRACE_CONFIG = "/api/spot/v1/trace/order/setTraceConfig"
    API_SPOT_V1_TRACE_ORDER_SPOT_INFO_LIST = "/api/spot/v1/trace/order/spotInfoList"
    API_SPOT_V1_TRACE_ORDER_UPDATE_TPSL = "/api/spot/v1/trace/order/updateTpsl"
    API_SPOT_V1_TRACE_PROFIT_PROFIT_HIS_DETAIL_LIST = "/api/spot/v1/trace/profit/profitHisDetailList"
    API_SPOT_V1_TRACE_PROFIT_PROFIT_HIS_LIST = "/api/spot/v1/trace/profit/profitHisList"
    API_SPOT_V1_TRACE_PROFIT_TOTAL_PROFIT_INFO = "/api/spot/v1/trace/profit/totalProfitInfo"
    API_SPOT_V1_TRACE_PROFIT_TOTAL_PROFIT_LIST = "/api/spot/v1/trace/profit/totalProfitList"
    API_SPOT_V1_TRACE_PROFIT_WAIT_PROFIT_DETAIL_LIST = "/api/spot/v1/trace/profit/waitProfitDetailList"
